loginFrameConfig:
    root_height: 400
    root_width: 600
    label_width: 25
    username_label_x: 150
    username_label_y: 100
    username_x: 270
    username_y: 100
    password_label_x: 150
    password_label_y: 225
    password_x: 270
    password_y: 225
    login_button_x: 200
    login_button_y: 350
senderFrameConfig:
    root_height: 800
    root_width: 1200
    label_width: 40
    state_label_x: 5
    state_label_y: 5
    change_state_button_x: 100
    change_state_button_y: 0
    subject_label_x: 15
    subject_label_y: 50
    subject_x: 20
    subject_y: 80
    subject_height: 1
    subject_width: 50
    sender_label_x: 535
    sender_label_y: 50
    sender_x: 540
    sender_y: 80
    sender_height: 1
    sender_width: 50
    receiver_label_x: 15
    receiver_label_y: 125
    receiver_x: 20
    receiver_y: 150
    receiver_height: 1
    receiver_width: 50
    text_label_x: 15
    text_label_y: 200
    text_x: 20
    text_y: 225
    text_height: 22
    text_width: 102
    send_button_x: 985
    send_button_y: 755
receiverFrameConfig:
    root_height: 800
    root_width: 1200
    label_width: 40
    state_label_x: 5
    state_label_y: 5
    change_state_button_x: 115
    change_state_button_y: 0
    mail_num_label_x: 350
    mail_num_label_y: 5
    subject_label_x: 15
    subject_label_y: 50
    subject_x: 20
    subject_y: 80
    subject_height: 1
    subject_width: 50
    sender_label_x: 535
    sender_label_y: 50
    sender_x: 540
    sender_y: 80
    sender_height: 1
    sender_width: 50
    receiver_label_x: 15
    receiver_label_y: 125
    receiver_x: 20
    receiver_y: 150
    receiver_height: 1
    receiver_width: 50
    mail_choose_label_x: 760
    mail_choose_label_y: 760
    mail_choose_x: 870
    mail_choose_y: 760
    mail_choose_height: 0
    mail_choose_width: 10
    text_label_x: 15
    text_label_y: 200
    text_x: 20
    text_y: 225
    text_height: 22
    text_width: 102
    send_button_x: 985
    send_button_y: 755
